project:
  type: website

metadata-files:
  - api/_sidebar.yml

website:
  title: "Docs"
  navbar:
    left:
      #- design.qmd
      - href: get-started/overview.qmd
        text: Get started
      - href: api/
        text: API
  sidebar:
    - id: get-started
      contents:
        - get-started/overview.qmd
        - get-started/advanced-programming.qmd
        - get-started/challenges.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

quartodoc:
  dir: api
  package: duckops
  sidebar: api/_sidebar.yml
  sections:
    - title: "Aggregations"
      explode: agg

    - title: "Blobs"
      explode: blob

    - title: "Datetime"
      explode: dt

    - title: "JSON"
      explode: json

    - title: "Nested"
      explode: nested

    - title: "Numeric"
      explode: num

    - title: "String"
      explode: str

    - title: "Unknown"
      explode: unknown
